spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url:  jdbc:postgresql://localhost:5432/quizapp_git
    username: postgres
    password: example
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
feature-toggles:
  configuration:
    application: xx6u2u3
    enviroment: gucjoiu
    profile: vt2myv6
# Configuração com H2
#spring:
#  datasource:
#    driverClassName: org.h2.Driver
#    url: jdbc:h2:mem:forum
#    username: sa
#    password:
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
#    properties:
#      hibernate:
#        show_sql: true
#        format_sql: true
#  h2:
#    console:
#      enabled: true
